### ISSUE TITLE
Add beautiful Kline charts or tradeview

### ISSUE THREAD

**Issue by onoriodelang** [MonsieurZbanowanYY/Crypto-App-UI-Flutter#1]
Use a custom Kline chart in your users interface

https://pub.dev/packages/k_chart
Or

https://github.com/GitHubYhb/HBLineChart

**Comment by MonsieurZbanowanYY** [comment]
Thanks for your feedback, this UI is only a demo - if you want to add the charts - please add them and make a pull request. If you make a pull request I will review it and probably accept it. Thanks!
